search.h

This merge incorporates the Move Ordering feature into the main branch. The Move Ordering branch includes the implementation of the MVV_LVA heuristic, Killer moves, and History moves.

Moveordering

---

search.h
stopwatch_t.h

Iterative deepening and replacement of fixed depth search with flexibile timed search.

Time control

---

search.h

Finally made TT pruning gain. The problem was that I was previously doing TT pruning also in PV nodes. Which often resulted in illegal moves. 
Score of dev vs old: 231 - 107 - 216  [0.612] 554
...      dev playing White: 110 - 44 - 123  [0.619] 277
...      dev playing Black: 121 - 63 - 93  [0.605] 277
...      White vs Black: 173 - 165 - 216  [0.507] 554
Elo difference: 79.1 +/- 22.8, LOS: 100.0 %, DrawRatio: 39.0 %
Finished match

Transposition table pruning

---

cli/uci.hpp
search/pv_table.hpp
search/search.hpp
search/search_data.hpp
search/time_keeper.hpp

Implementation of time management, pv table and simple search data data structure

Search prerequesities

---

chess_board/board.hpp
cli/uci.hpp
search/pv_table.hpp
search/search.hpp
search/search_data.hpp

Simple alpha beta pruning with fixed depth. From here I can sprt new updates

Alpha beta pruning

---

cli/uci.hpp
search/search.hpp
search/search_data.hpp

TC=10+0.1
Score of dev vs old: 344 - 166 - 82  [0.650] 592
...      dev playing White: 184 - 68 - 43  [0.697] 295
...      dev playing Black: 160 - 98 - 39  [0.604] 297
...      White vs Black: 282 - 228 - 82  [0.546] 592
Elo difference: 107.8 +/- 27.0, LOS: 100.0 %, DrawRatio: 13.9 %
SPRT: llr 2.95 (100.2%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

iterative deepening

---

chess_board/board.hpp
chess_board/chess_move.hpp
move_generation/move_generator.hpp
move_generation/move_list.hpp
search/move_ordering/move_ordering.hpp
search/search.hpp
search/transposition_table.hpp

TC=10+0.1
Score of dev vs old: 171 - 23 - 38  [0.819] 232
...      dev playing White: 92 - 8 - 16  [0.862] 116
...      dev playing Black: 79 - 15 - 22  [0.776] 116
...      White vs Black: 107 - 87 - 38  [0.543] 232
Elo difference: 262.2 +/- 50.1, LOS: 100.0 %, DrawRatio: 16.4 %
Finished match

Transposition table

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 618 - 473 - 585  [0.543] 1676
...      dev playing White: 358 - 205 - 275  [0.591] 838
...      dev playing Black: 260 - 268 - 310  [0.495] 838
...      White vs Black: 626 - 465 - 585  [0.548] 1676
Elo difference: 30.1 +/- 13.4, LOS: 100.0 %, DrawRatio: 34.9 %
Finished match

PVS implementation

---

chess_board/board.hpp
move_generation/move_generator.hpp
move_generation/move_list.hpp

Bug in printing of uci move after refactoring

Revert "Movegen refactor"

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 719 - 562 - 540  [0.543] 1821
...      dev playing White: 433 - 221 - 258  [0.616] 912
...      dev playing Black: 286 - 341 - 282  [0.470] 909
...      White vs Black: 774 - 507 - 540  [0.573] 1821
Elo difference: 30.0 +/- 13.4, LOS: 100.0 %, DrawRatio: 29.7 %
Finished match

tt pruning

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 220 - 92 - 176  [0.631] 488
...      dev playing White: 129 - 31 - 84  [0.701] 244
...      dev playing Black: 91 - 61 - 92  [0.561] 244
...      White vs Black: 190 - 122 - 176  [0.570] 488
Elo difference: 93.3 +/- 25.0, LOS: 100.0 %, DrawRatio: 36.1 %
SPRT: llr 2.95 (100.1%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Aspiration window

---

chess_board/board.hpp
cli/uci.hpp
search/search.hpp

Score of dev vs old: 525 - 389 - 575  [0.546] 1489
...      dev playing White: 334 - 140 - 272  [0.630] 746
...      dev playing Black: 191 - 249 - 303  [0.461] 743
...      White vs Black: 583 - 331 - 575  [0.585] 1489
Elo difference: 31.8 +/- 13.8, LOS: 100.0 %, DrawRatio: 38.6 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Null move pruning

---

chess_board/board.hpp
chess_board/chess_move.hpp
move_generation/move_generator.hpp
move_generation/move_list.hpp
search/move_ordering/see.hpp
search/quiescence_search.hpp
search/search.hpp

Fix discovery bugs in enpassant.
No elo changes.

Movegen bug fix

---

search/search.hpp
search/search_data.hpp
search/time_keeper.hpp

Score of dev vs old: 471 - 356 - 790  [0.536] 1617
...      dev playing White: 399 - 48 - 363  [0.717] 810
...      dev playing Black: 72 - 308 - 427  [0.354] 807
...      White vs Black: 707 - 120 - 790  [0.682] 1617
Elo difference: 24.8 +/- 12.1, LOS: 100.0 %, DrawRatio: 48.9 %
SPRT: llr 2.93 (99.4%), lbound -2.94, ubound 2.94
Finished match

Add soft-tm

---

chess_board/chess_move.hpp
search/move_ordering/see.hpp

Score of dev vs old: 756 - 633 - 1358  [0.522] 2747
...      dev playing White: 648 - 88 - 637  [0.704] 1373
...      dev playing Black: 108 - 545 - 721  [0.341] 1374
...      White vs Black: 1193 - 196 - 1358  [0.681] 2747
Elo difference: 15.6 +/- 9.2, LOS: 100.0 %, DrawRatio: 49.4 %
SPRT: llr 2.95 (100.1%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Fix see pruning

---

cli/uci.hpp
search/search.hpp
search/search_data.hpp

Remove old butterfly board

---

search/time_keeper.hpp

Fix includes in timekeeper to enable compiling on Linux devices.
Thanks to [Roelof Berkepeis](https://github.com/tissatussa) for discovering and also solving the [problem](https://github.com/martinnovaak/motor/issues/82) .

Fix includes for linux build

---

search/search.hpp

Add depth condition into razoring

---

search/search.hpp
search/search_data.hpp
search/time_keeper.hpp

node tm (#97)

---

chess_board/board.hpp
cli/uci.hpp
search/move_ordering/move_ordering.hpp
search/search.hpp
search/tables/history_table.hpp
search/tables/lmr_table.hpp

Elo   | 3.85 +- 2.92 (95%)
SPRT  | 30.0+0.30s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 14254 W: 3284 L: 3126 D: 7844
Penta | [21, 1685, 3576, 1805, 40]
Bench: 5501461

SPSA 5000 iterations

---

chess_board/board.hpp
cli/uci.hpp
move_generation/move_list.hpp
search/search.hpp
search/tables/history_table.hpp
search/tables/transposition_table.hpp

Preparation for release

---

search/bench.hpp
search/search.hpp

Elo   | 5.00 +- 3.58 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10502 W: 2612 L: 2461 D: 5429
Penta | [44, 1247, 2542, 1350, 68]
Bench: 3993524

Cutnode lmr

---

cli/uci.hpp
search/bench.hpp
search/search.hpp
search/search_data.hpp
search/time_keeper.hpp

Add support of go nodes command

---

chess_board/board.hpp
cli/uci.hpp
search/search.hpp
search/tables/history_table.hpp

Elo   | 5.88 +- 3.95 (95%)
Games | N: 8278 W: 2040 L: 1900 D: 4338
Penta | [23, 970, 2034, 1068, 44]
Bench: 4261824

Correction evaluation history

---

cli/uci.hpp
evaluation/nnue.hpp

Elo   | 3.66 +- 2.85 (95%)
Games | N: 17296 W: 4546 L: 4364 D: 8386
Penta | [119, 2055, 4123, 2227, 124]
Bench: 5379761

3 input buckets

---

search/search.hpp

Elo   | 4.25 +- 3.16 (95%)
Games | N: 12752 W: 3100 L: 2944 D: 6708
Penta | [37, 1505, 3158, 1617, 59]
Bench: 4363180

Cutnode negext

---

executioner/makemove.hpp

Elo   | 6.75 +- 4.28 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6954 W: 1700 L: 1565 D: 3689
Penta | [38, 755, 1736, 930, 18]
Bench: 3084444

Material scale

---

search/search.hpp

Thanks to [zzzzz151](https://github.com/zzzzz151) for correcting my cutnode implementation.

Pvs cutnode fix

---

evaluation/nnue.hpp

Elo   | 6.36 +- 4.18 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7864 W: 1998 L: 1854 D: 4012
Penta | [48, 905, 1881, 1051, 47]
Bench: 3147055

Finetune with ranger optimizer

---

search/time_keeper.hpp

Elo   | 5.61 +- 3.78 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8422 W: 2035 L: 1899 D: 4488
Penta | [29, 907, 2207, 1035, 33]

Tm stability2

---

search/move_ordering/move_ordering.hpp
search/search_data.hpp

Elo   | 1.70 +- 3.19 (95%)
LLR   | 2.97 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 12478 W: 3036 L: 2975 D: 6467
Penta | [58, 1458, 3137, 1537, 49]
Bench: 3290412

Remove second killer

---

evaluation/nnue.hpp

Elo   | 11.78 +- 5.89 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3452 W: 846 L: 729 D: 1877
Penta | [7, 360, 876, 475, 8]
Bench: 2761566

New net hl size 1536

---

search/search.hpp
search/search_data.hpp
search/tables/transposition_table.hpp

Elo   | 16.28 +- 6.90 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=16MB
Games | N: 2328 W: 551 L: 442 D: 1335
Penta | [1, 219, 619, 320, 5]
Elo   | 8.08 +- 3.91 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=4MB
Games | N: 8820 W: 2241 L: 2036 D: 4543
Penta | [47, 977, 2172, 1152, 62]
Bench: 2803419

Introduce TT clusters

---

chess_board/board.hpp
search/quiescence_search.hpp
search/search.hpp

Elo   | 2.76 +- 1.99 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 31302 W: 7513 L: 7264 D: 16525
Penta | [82, 3721, 7825, 3912, 111]

Quiescence futility pruning

---

cli/uci.hpp
search/quiescence_search.hpp
search/search.hpp
search/tables/transposition_table.hpp

Elo   | 2.38 +- 1.80 (95%)
Games | N: 38344 W: 9269 L: 9006 D: 20069
Penta | [124, 4507, 9676, 4712, 153]
Bench: 4031781

Save tt move only on alpha raise

---

search/search.hpp

Elo   | 2.41 +- 1.82 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 37578 W: 9137 L: 8876 D: 19565
Penta | [130, 4356, 9573, 4583, 147]
Bench: 3999863

Negext beta

---

search/search.hpp

Elo   | 2.21 +- 1.71 (95%)
Games | N: 42982 W: 10418 L: 10144 D: 22420
Penta | [140, 5081, 10795, 5315, 160]
Bench: 4006456

Smaller aspiration windows 

---

search/search.hpp

Elo   | 2.01 +- 1.58 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.00]
Games | N: 47966 W: 11744 L: 11466 D: 24756
Penta | [132, 5549, 12351, 5811, 140]
Bench: 5137623

Triple extension

---

chess_board/board.hpp
search/quiescence_search.hpp
search/search.hpp

Elo   | 2.51 +- 2.75 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 14120 W: 3347 L: 3245 D: 7528
Penta | [36, 1428, 4036, 1518, 42]
Bench: 5039699

threefold repetition

---

search/tables/transposition_table.hpp
search/time_keeper.hpp

Elo   | 5.36 +- 3.05 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 13034 W: 3361 L: 3160 D: 6513
Penta | [28, 1484, 3303, 1663, 39]
Bench: 4581906

New TT replacement scheme

---

search/tables/history_table.hpp

Elo   | 1.15 +- 0.88 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 157032 W: 39199 L: 38680 D: 79153
Penta | [386, 18726, 39814, 19163, 427]
Bench: 4600056

Pawn history

---

search/search.hpp

Elo   | 3.99 +- 3.50 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 10008 W: 2530 L: 2415 D: 5063
Penta | [26, 1155, 2530, 1264, 29]
Bench: 4395380

Same lmr in pv and nonpv nodes
