martinnovaak/motor

chess_board/chess_move.hpp
search/move_ordering/move_ordering.hpp
search/search.hpp
search/search_data.hpp

TC=10+0.1
MVV-LVA
Score of dev vs old: 769 - 599 - 417  [0.548] 1785
...      dev playing White: 447 - 239 - 206  [0.617] 892
...      dev playing Black: 322 - 360 - 211  [0.479] 893
...      White vs Black: 807 - 561 - 417  [0.569] 1785
Elo difference: 33.2 +/- 14.1, LOS: 100.0 %, DrawRatio: 23.4 %
SPRT: llr 2.96 (100.5%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match
Killers
Score of dev vs old: 628 - 465 - 371  [0.556] 1464
...      dev playing White: 356 - 201 - 175  [0.606] 732
...      dev playing Black: 272 - 264 - 196  [0.505] 732
...      White vs Black: 620 - 473 - 371  [0.550] 1464
Elo difference: 38.8 +/- 15.4, LOS: 100.0 %, DrawRatio: 25.3 %
Finished match
History
Score of dev vs old: 514 - 355 …

MVV-LVA, Killer moves and history moves implementation

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 379 - 220 - 190  [0.601] 789
...      dev playing White: 215 - 86 - 93  [0.664] 394
...      dev playing Black: 164 - 134 - 97  [0.538] 395
...      White vs Black: 349 - 250 - 190  [0.563] 789
Elo difference: 71.0 +/- 21.4, LOS: 100.0 %, DrawRatio: 24.1 %
SPRT: llr 2.95 (100.2%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

check extension

---

search/move_ordering/move_ordering.hpp
search/quiescence_search.hpp

TC=10+0.1
Score of dev vs old: 395 - 248 - 285  [0.579] 928
...      dev playing White: 223 - 106 - 136  [0.626] 465
...      dev playing Black: 172 - 142 - 149  [0.532] 463
...      White vs Black: 365 - 278 - 285  [0.547] 928
Elo difference: 55.5 +/- 18.7, LOS: 100.0 %, DrawRatio: 30.7 %
Finished match

Add MVV-LVA into quiescence search

---

chess_board/board.hpp
search/move_ordering/move_ordering.hpp
search/search.hpp
search/search_data.hpp

TC=10+0.1
Score of dev vs old: 719 - 558 - 481  [0.546] 1758
...      dev playing White: 412 - 224 - 242  [0.607] 878
...      dev playing Black: 307 - 334 - 239  [0.485] 880
...      White vs Black: 746 - 531 - 481  [0.561] 1758
Elo difference: 31.9 +/- 13.9, LOS: 100.0 %, DrawRatio: 27.4 %
SPRT: llr 2.95 (100.2%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

See implementation

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 302 - 155 - 186  [0.614] 643
...      dev playing White: 171 - 60 - 92  [0.672] 323
...      dev playing Black: 131 - 95 - 94  [0.556] 320
...      White vs Black: 266 - 191 - 186  [0.558] 643
Elo difference: 80.9 +/- 23.0, LOS: 100.0 %, DrawRatio: 28.9 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Reverse futility pruning

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 435 - 292 - 367  [0.565] 1094
...      dev playing White: 266 - 100 - 181  [0.652] 547
...      dev playing Black: 169 - 192 - 186  [0.479] 547
...      White vs Black: 458 - 269 - 367  [0.586] 1094
Elo difference: 45.7 +/- 16.8, LOS: 100.0 %, DrawRatio: 33.5 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Late move reduction

---

chess_board/chess_move.hpp
search/move_ordering/move_ordering.hpp
search/move_ordering/see.hpp
search/quiescence_search.hpp

TC=10+0.1
Score of dev vs old: 811 - 671 - 1002  [0.528] 2484
...      dev playing White: 516 - 237 - 489  [0.612] 1242
...      dev playing Black: 295 - 434 - 513  [0.444] 1242
...      White vs Black: 950 - 532 - 1002  [0.584] 2484
Elo difference: 19.6 +/- 10.5, LOS: 100.0 %, DrawRatio: 40.3 %
Finished match

QS SEE ordering

---

search/search.hpp

Score of dev vs old: 990 - 844 - 1204  [0.524] 3038
...      dev playing White: 654 - 272 - 593  [0.626] 1519
...      dev playing Black: 336 - 572 - 611  [0.422] 1519
...      White vs Black: 1226 - 608 - 1204  [0.602] 3038
Elo difference: 16.7 +/- 9.6, LOS: 100.0 %, DrawRatio: 39.6 %
SPRT: llr 2.97 (100.7%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Simple late move pruning

---

search/search.hpp
search/search_data.hpp

Score of dev vs old: 720 - 585 - 937  [0.530] 2242
...      dev playing White: 465 - 198 - 459  [0.619] 1122
...      dev playing Black: 255 - 387 - 478  [0.441] 1120
...      White vs Black: 852 - 453 - 937  [0.589] 2242
Elo difference: 20.9 +/- 11.0, LOS: 100.0 %, DrawRatio: 41.8 %
SPRT: llr 2.95 (100.1%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Timekeeper bug fix

---

search/move_ordering/move_ordering.hpp
search/search.hpp
search/search_data.hpp

TC=10+0.1
Score of dev vs old: 717 - 582 - 943  [0.530] 2242
...      dev playing White: 482 - 195 - 444  [0.628] 1121
...      dev playing Black: 235 - 387 - 499  [0.432] 1121
...      White vs Black: 869 - 430 - 943  [0.598] 2242
Elo difference: 20.9 +/- 10.9, LOS: 100.0 %, DrawRatio: 42.1 %
SPRT: llr 2.96 (100.6%), lbound -2.94, ubound 2.94 - H1 was accepted

Counter move heuristic

---

search/search.hpp

TC=10+0.1
Score of dev vs old: 1033 - 890 - 1383  [0.522] 3306
...      dev playing White: 665 - 264 - 724  [0.621] 1653
...      dev playing Black: 368 - 626 - 659  [0.422] 1653
...      White vs Black: 1291 - 632 - 1383  [0.600] 3306
Elo difference: 15.0 +/- 9.0, LOS: 99.9 %, DrawRatio: 41.8 %
Finished match

Internal iterative reduction

---

search/search.hpp

Score of dev vs old: 623 - 488 - 764  [0.536] 1875
...      dev playing White: 417 - 152 - 369  [0.641] 938
...      dev playing Black: 206 - 336 - 395  [0.431] 937
...      White vs Black: 753 - 358 - 764  [0.605] 1875
Elo difference: 25.1 +/- 12.1, LOS: 100.0 %, DrawRatio: 40.7 %
SPRT: llr 2.96 (100.7%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

razoring on non tt hits

---

chess_board/chess_move.hpp
cli/uci.hpp
main.cpp
search/bench.hpp
search/search.hpp
search/search_data.hpp

Score of dev vs old: 951 - 818 - 1567  [0.520] 3336
...      dev playing White: 710 - 192 - 766  [0.655] 1668
...      dev playing Black: 241 - 626 - 801  [0.385] 1668
...      White vs Black: 1336 - 433 - 1567  [0.635] 3336
Elo difference: 13.9 +/- 8.6, LOS: 99.9 %, DrawRatio: 47.0 %
SPRT: llr 2.96 (100.7%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

New lmp formula

---

chess_board/board.hpp
chess_board/chess_move.hpp
cli/uci.hpp
move_generation/move_generator.hpp
search/move_ordering/see.hpp
search/quiescence_search.hpp
search/search.hpp
search/search_data.hpp

New legal move generator
- removing the precalculation of check on a chess moves generation
- chess move structure now fits 16 bits
- adding static eval (16 bits) into transposition table entry 
8+0.08 test:
```
Score of dev vs old: 650 - 531 - 1181  [0.525] 2362
...      dev playing White: 536 - 74 - 570  [0.696] 1180
...      dev playing Black: 114 - 457 - 611  [0.355] 1182
...      White vs Black: 993 - 188 - 1181  [0.670] 2362
Elo difference: 17.5 +/- 9.9, LOS: 100.0 %, DrawRatio: 50.0 %
SPRT: llr 2.95 (100.1%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match
```

New faster generator

---

search/search.hpp

Score of dev vs old: 1598 - 1454 - 3380  [0.511] 6432
...      dev playing White: 1360 - 214 - 1643  [0.678] 3217
...      dev playing Black: 238 - 1240 - 1737  [0.344] 3215
...      White vs Black: 2600 - 452 - 3380  [0.667] 6432
Elo difference: 7.8 +/- 5.8, LOS: 99.5 %, DrawRatio: 52.5 %
SPRT: llr 2.97 (100.7%), lbound -2.94, ubound 2.94 - H1 was accepted
Finished match

Add futility pruning

---

evaluation/nnue.hpp
executioner/makemove.hpp

New arch: (768 x 6 -> 1024) x 2 -> 1 HM
STC:
```
Elo   | 27.10 +- 9.69 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1606 W: 482 L: 357 D: 767
Penta | [8, 160, 354, 261, 20]
```
LTC: 
```
Elo   | 17.66 +- 7.55 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2382 W: 658 L: 537 D: 1187
Penta | [5, 259, 555, 354, 18]
```
Bench: 4211923

King input buckets

---

search/quiescence_search.hpp
search/search.hpp

STC:
```
Elo   | 13.37 +- 6.32 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3146 W: 785 L: 664 D: 1697
Penta | [10, 323, 791, 434, 15]
```
LTC:
```
Elo   | 12.47 +- 5.89 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3094 W: 732 L: 621 D: 1741
Penta | [2, 291, 856, 390, 8]
```

No check extension + qs evasions

---

search/quiescence_search.hpp
search/search.hpp
search/search_data.hpp
search/tables/transposition_table.hpp

This PR makes the following changes:
- adds new functions for storing and retrieving TT entries
- enables TT cutoffs for mate values
- adjusts TT mate values based on plies to be accurate
- frees up 32 bits in the TT entry to be used later for something else (e.g. ageing)
- changes to fail-hard in NMP if the returned score is a mate value
Earlier version passed gainer bounds for endgames.epd with adjudication turned off:
```
Elo   | 13.69 +- 5.46 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2108 W: 353 L: 270 D: 1485
Penta | [0, 103, 766, 184, 1]
https://zzzzz151.pythonanywhere.com/test/334/
```
Passed non-regression under regular testing procedures:
```
Elo   | -0.40 +- 1.68 (95%)
LLR   | 2.96 …
```

Enable TT cutoffs for mate score values

---

search/search.hpp

Elo   | 4.45 +- 3.25 (95%)
Games | N: 11632 W: 2853 L: 2704 D: 6075
Penta | [40, 1308, 2972, 1455, 41]
Bench: 3436807

lmr depth move score

---

search/move_ordering/move_ordering.hpp
search/search.hpp
search/search_data.hpp

Elo   | 3.05 +- 2.16 (95%)
Games | N: 27838 W: 6744 L: 6500 D: 14594
Penta | [103, 3310, 6902, 3448, 156]
Bench: 3198318

Remove counter move heuristic

---

search/search.hpp

Elo   | 2.79 +- 2.01 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 30364 W: 7264 L: 7020 D: 16080
Penta | [110, 3464, 7790, 3708, 110]
Bench: 2680495

Probcut with see threshold

---

search/search.hpp

Elo   | 2.41 +- 1.81 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 37456 W: 8893 L: 8633 D: 19930
Penta | [124, 4347, 9535, 4589, 133]
Bench: 3053409

No depth condition in SEE pruning

---

search/search.hpp

Elo   | 4.09 +- 3.50 (95%)
SPRT  | 14.0+0.14s Threads=1 Hash=32MB
LLR   | 2.95 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 9858 W: 2298 L: 2182 D: 5378
Penta | [21, 1140, 2490, 1258, 20]
Bench: 1814424

Remove check extensions completely

---

chess_board/board.hpp
cli/uci.hpp
search/search.hpp
search/tables/history_table.hpp

Idea from Starzix. Correct static evaluation based on nonpawn structure
Elo   | 3.30 +- 2.25 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 24942 W: 6088 L: 5851 D: 13003
Penta | [92, 2911, 6235, 3134, 99]
Bench: 1960865

Nonpawn structure correction table

---

cli/uci.hpp
search/move_ordering/move_ordering.hpp
search/quiescence_search.hpp
search/search.hpp
search/tables/history_table.hpp

Elo   | 2.22 +- 1.71 (95%)
Games | N: 43042 W: 10600 L: 10325 D: 22117
Penta | [132, 5145, 10738, 5328, 178]
Bench: 4822216

Add material structure history into move ordering

---

search/search.hpp

Elo   | 1.56 +- 3.04 (95%)
LLR   | 3.02 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 13104 W: 3116 L: 3057 D: 6931
Penta | [30, 1555, 3332, 1596, 39]
Bench: 3959159

corrhist fix

---

search/search.hpp

Elo   | 3.23 +- 2.24 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 24208 W: 5805 L: 5580 D: 12823
Penta | [68, 2785, 6174, 3008, 69]
Bench: 4402854

Big correction weights

---

chess_board/board.hpp
cli/uci.hpp
search/quiescence_search.hpp
search/search.hpp
search/tables/history_table.hpp

Idea from [Sirius](https://github.com/mcthouacbb/Sirius). Correct static evaluation based on minor and major piece structures. 
Elo   | 1.91 +- 1.51 (95%)
LLR   | 2.96 (-2.25, 2.89) [0.00, 3.00]
Games | N: 54282 W: 13075 L: 12776 D: 28431
Penta | [169, 6425, 13684, 6664, 199]
Bench: 3924360

Major-Minor correction history

---

cli/uci.hpp
search/search.hpp
search/tables/history_table.hpp

Elo   | 1.26 +- 2.18 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 25082 W: 5960 L: 5869 D: 13253
Penta | [47, 2958, 6467, 2995, 74]
Bench: 3620775

Remove material correction history

---

search/quiescence_search.hpp
search/search.hpp
search/tables/history_table.hpp

Correct static evaluation based on last two played moves
Elo   | 2.83 +- 2.04 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 29316 W: 7109 L: 6870 D: 15337
Penta | [77, 3410, 7461, 3617, 93]

Concorrde - Continuation correction history

---

search/move_ordering/move_ordering.hpp

Elo   | 6.38 +- 3.38 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.00]
Games | N: 10782 W: 2631 L: 2433 D: 5718
Penta | [29, 1211, 2717, 1401, 33]

Change see threshold based on capture history score

---

search/search.hpp

Change conditions for correction history update from corrected eval to raw evaluation
Elo   | 3.30 +- 2.27 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 23920 W: 5863 L: 5636 D: 12421
Penta | [70, 2769, 6070, 2966, 85]
Bench: 4131841

Change conditions for correction history update

---

search/search.hpp

Elo   | 3.36 +- 2.31 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 23350 W: 5893 L: 5667 D: 11790
Penta | [65, 2744, 5839, 2954, 73]
Bench: 4340505

Fail firm in rfp

---

search/quiescence_search.hpp

Elo   | 2.61 +- 2.88 (95%)
LLR   | 2.93 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 14386 W: 3583 L: 3475 D: 7328
Penta | [25, 1681, 3691, 1753, 43]
Bench: 4824822

Fix qsearch correction

---

search/search.hpp

Elo   | 2.61 +- 1.93 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 32070 W: 7959 L: 7718 D: 16393
Penta | [82, 3700, 8220, 3961, 72]

Tweaking evaluation ration value for corrhist update
